apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginxweave
  name: nginxweave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxweave
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginxweave
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        resources: {}
status: {}
